[build]
  publish = "public"
  command = "yarn run build"
[build.environment]
  YARN_VERSION = "1.16.0"
[[headers]]
  for = "/rss.xml"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"
    Access-Control-Allow-Headers = "*"
